# Generated by Django 3.1.4 on 2021-01-11 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
